<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="33" started-at="2018-10-12T13:55:03Z" finished-at="2018-10-12T13:55:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="33" started-at="2018-10-12T13:55:03Z" finished-at="2018-10-12T13:55:03Z">
      <class name="com.egtinteractive.testing.framework.Tests">
        <test-method status="PASS" signature="beforetest1()[pri:0, instance:com.egtinteractive.testing.framework.Tests@51efea79]" name="beforetest1" is-config="true" duration-ms="7" started-at="2018-10-12T13:55:03Z" finished-at="2018-10-12T13:55:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetest1 -->
        <test-method status="PASS" signature="beforetest2()[pri:0, instance:com.egtinteractive.testing.framework.Tests@51efea79]" name="beforetest2" is-config="true" duration-ms="0" started-at="2018-10-12T13:55:03Z" finished-at="2018-10-12T13:55:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetest2 -->
        <test-method status="FAIL" signature="test1()[pri:0, instance:com.egtinteractive.testing.framework.Tests@51efea79]" name="test1" duration-ms="4" started-at="2018-10-12T13:55:03Z" finished-at="2018-10-12T13:55:03Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException
at com.egtinteractive.testing.framework.Tests.test1(Tests.java:12)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="test2()[pri:0, instance:com.egtinteractive.testing.framework.Tests@51efea79]" name="test2" duration-ms="1" started-at="2018-10-12T13:55:03Z" finished-at="2018-10-12T13:55:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="test3()[pri:0, instance:com.egtinteractive.testing.framework.Tests@51efea79]" name="test3" duration-ms="1" started-at="2018-10-12T13:55:03Z" finished-at="2018-10-12T13:55:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="PASS" signature="aftertest2()[pri:0, instance:com.egtinteractive.testing.framework.Tests@51efea79]" name="aftertest2" is-config="true" duration-ms="0" started-at="2018-10-12T13:55:03Z" finished-at="2018-10-12T13:55:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertest2 -->
        <test-method status="PASS" signature="aftertest1()[pri:0, instance:com.egtinteractive.testing.framework.Tests@51efea79]" name="aftertest1" is-config="true" duration-ms="0" started-at="2018-10-12T13:55:03Z" finished-at="2018-10-12T13:55:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertest1 -->
        <test-method status="PASS" signature="aftertest3()[pri:0, instance:com.egtinteractive.testing.framework.Tests@51efea79]" name="aftertest3" is-config="true" duration-ms="0" started-at="2018-10-12T13:55:03Z" finished-at="2018-10-12T13:55:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertest3 -->
      </class> <!-- com.egtinteractive.testing.framework.Tests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
